import math

# print(abs(-10))
# print(math.ceil(5.1))
# print(math.exp(2))
# print(math.fabs(-15.2))
# print(math.floor(6.5))
# print(math.log(2))
# print(math.log10(1))
# print(max(5, 6))
# print(math.pow(2, 3))
# print(math.sqrt(16))
# print(math.sin(0))
# print(math.radians(10))
print(math.factorial(5))
print(math.isinf(50))
print(math.isnan(5))
print(math.fmod(8, 2))
print(math.fsum([1,2,3,4,5]))